routes/web.php
<?php

use App\Models\Category;
use App\Models\Color;
use App\Models\Size;
use App\Models\Vendor;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ColorController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\GeneralSettingsController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\Front\CustomerController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->to('home');

});
Route::get('/home', [\App\Http\Controllers\Front\PagesController::class, 'index'])->name('home');

Route::view('/admin/login', 'admin.login');

Route::get('login-popup', function () {
    return view('front.loginPopup');
});

Route::get('add-address', function () {
    return view('front.addAddress');
});
Route::view('contact-us', 'front.contact-us');

// Route::view('/dashboard', 'admin.index')->middleware(['auth'])->name('dashboard');
Route::get('/dashboard', [\App\Http\Controllers\HomeController::class, 'index'])->middleware(['auth'])->name('dashboard');
\Illuminate\Support\Facades\Auth::routes();
//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//---------------------------Routes for guest users of front site--------------------------------------//
Route::group(['namespace' => 'Front'], function () {
    Route::get('product-list/{category_name}', [\App\Http\Controllers\Front\ProductController::class, 'getProducts'])->name('getProducts');
    Route::get('product-detail/{id}', [\App\Http\Controllers\Front\ProductController::class, 'productDetail'])->name('productDetail');
    Route::get('product_category_filter', [\App\Http\Controllers\Front\ProductController::class, 'categoryFilter'])->name('categoryFilter');
    Route::get('product_name_filter', [\App\Http\Controllers\Front\ProductController::class, 'productNameFilter'])->name('productNameFilter');
    Route::get('product_price_filter', [\App\Http\Controllers\Front\ProductController::class, 'priceFilter'])->name('priceFilter');
    Route::get('get-color-sizes/{color_id}/{variant_id}', [\App\Http\Controllers\Front\ProductController::class, 'getColorSizes'])->name('getColorSizes');
    Route::get('product_size-filter/{type}/{min}/{max}/{size}', [\App\Http\Controllers\Front\ProductController::class, 'sizeFilter'])->name('sizeFilter');
    Route::get('product_color-filter/{type}/{min}/{max}/{size}', [\App\Http\Controllers\Front\ProductController::class, 'colorFilter'])->name('colorFilter');
    Route::get('product_size_color-filter/{type}/{min}/{max}/{size}/{color}', [\App\Http\Controllers\Front\ProductController::class, 'sizeColorFilter'])->name('sizeColorFilter');
    Route::get('product_wishlist_update/{product_id}/{variant_id}', [\App\Http\Controllers\Front\ProductController::class, 'productWishlistUpdate'])->name('productWishlistUpdate');
    Route::get('trackOrder', [\App\Http\Controllers\Front\ProductController::class, 'trackOrder'])->name('trackOrder');

   Route::get('product_search_filter/{search}/{color}/{size}/{min_max}/{price_limit}', [\App\Http\Controllers\Front\ProductController::class, 'productSearchFiter'])->name('productSearchFiter');
   Route::get('product_category_filter/{search}/{color}/{size}/{min_max}/{price_limit}', [\App\Http\Controllers\Front\ProductController::class, 'productCategoryFiter'])->name('productCategoryFiter');

     Route::get('clear_cart', [\App\Http\Controllers\Front\CartController::class, 'clearCart'])->name('clearCart');

});

Route::get('cart', [\App\Http\Controllers\Front\WishlistProducts::class, 'cartItems'])->name('cart');
Route::get('product_cart_update/{variant_id}/{qty?}', [\App\Http\Controllers\Front\WishlistProducts::class, 'productCartUpdate'])->name('productCartUpdate');
Route::get('remove-cart-item/{variant_id}', [\App\Http\Controllers\Front\WishlistProducts::class, 'removeCartItem'])->name('removeCartItem');
Route::get('get-cart-item', [\App\Http\Controllers\Front\WishlistProducts::class, 'getCartItems'])->name('getCartItems');


Route::get('check_coupon_validity/{coupon}', [\App\Http\Controllers\Front\CartController::class, 'checkCouponValidity'])->name('checkCouponValidity');


Route::middleware(['auth'])->group(function () {
    Route::resource('roles', RoleController::class);
    Route::get('admin-profile',[UserController::class,'adminProfile'])->name('adminProfile');
    Route::resource('users', UserController::class);
    Route::resource('permissions', PermissionController::class);
    Route::resource('colors', ColorController::class);
    Route::resource('sizes', \App\Http\Controllers\SizeController::class);
    Route::get('category_images', [CategoriesController::class, 'getCategoryImages'])->name('getCategoryImages');
    Route::resource('categories', CategoriesController::class);
    Route::get('get_images', [ProductController::class, 'getImages'])->name('getImages');
    Route::post('storeProduct', [ProductController::class, 'storeProduct'])->name('storeProduct');
//    Route::get('/product', function () {});
    Route::get('products/variants/{id}', [ProductController::class, 'getProdcutVariant'])->name('get_product_variant');
    Route::get('products/edit_variants/{variant_id}', [ProductController::class, 'editVariant'])->name('edit_variant');
    Route::post('products/update_variants/{variant_id}', [ProductController::class, 'updateVariant'])->name('update_variant');
    Route::delete('products_variants_delete/{variant_id}', [ProductController::class, 'deleteVariant'])->name('delete_variant');
    Route::resource('products', ProductController::class);
    Route::resource('general-settings', GeneralSettingsController::class);
    Route::get('assign-coupon-page',[CouponController::class,'assignCouponsList'])->name('assignCouponsList');
    Route::get('get-remaining-coupons',[CouponController::class,'getRemainingCouponsToAssign'])->name('getRemainingCouponsToAssign');
    Route::post('search-customer',[CouponController::class,'searchCustomer'])->name('searchCustomer');
    Route::post('assign-coupons',[CouponController::class,'assignCouponToCustomer'])->name('assignCouponToCustomer');
    Route::resource('coupons', CouponController::class);
    Route::resource('banners', \App\Http\Controllers\BannerController::class);
    Route::get('banner_images', [\App\Http\Controllers\BannerController::class, 'getBannerImages'])->name('getBannerImages');
    Route::post('getFirstcategory', [ProductController::class, 'getFirstcategory'])->name('getFirstcategory');
    Route::post('getSecondChildCategory', [ProductController::class, 'getSecondChildCategory'])->name('getSecondChildCategory');

    Route::get('orders-page', [\App\Http\Controllers\OrderController::class, 'index'])->name('orders');
    Route::get('changeOrderStatus/{id}', [\App\Http\Controllers\OrderController::class, 'changeStatus'])->name('changeStatus');
    Route::get('updateStatus', [\App\Http\Controllers\OrderController::class, 'updateStatus'])->name('updateStatus');


    Route::get('/failed_jobs', [\App\Http\Controllers\JobController::class, 'index'])->name('jobs.index');

   Route::get('/job/retry/{id}', function ($id) {

    Artisan::call('config:cache');
    Artisan::queue('queue:restart');

    sleep(2);
      $exitCode = Artisan::call('queue:retry', [
        'id' => $id
    ]);
   return Redirect::back();
});

    Route::group(['namespace' => 'Front'], function () {
        Route::post('update_profile', [CustomerController::class, 'updateProfile'])->name('update_profile');
        Route::post('save_address', [\App\Http\Controllers\Front\WishlistProducts::class, 'saveAddress'])->name('save_address');
        Route::get('change_address_status/{id}/{status}', [\App\Http\Controllers\Front\WishlistProducts::class, 'changeAddressStatus'])->name('changeAddressStatus');
        Route::get('profile', [\App\Http\Controllers\Front\WishlistProducts::class, 'cartOrders'])->name('cartOrders');
        Route::get('wishlist', [\App\Http\Controllers\Front\WishlistProducts::class, 'index'])->name('wishlist');
        Route::get('remove-wishlist/{id}/{variant_id}', [\App\Http\Controllers\Front\WishlistProducts::class, 'removeWishlistItem'])->name('removeWishlistItem');
        /*
                Route::get('remove-cart-item/{variant_id}', [\App\Http\Controllers\Front\WishlistProducts::class, 'removeCartItem'])->name('removeCartItem');
        */
        //Route::post('order-place', [\App\Http\Controllers\Front\WishlistProducts::class, 'orderPlace'])->name('orderPlace');
        Route::post('orderPlace', [\App\Http\Controllers\Front\WishlistProducts::class, 'orderPlace'])->name('orderPlace');
        Route::post('save-rating/{product_id}/{variant_id}', [\App\Http\Controllers\Front\WishlistProducts::class, 'saveRating'])->name('saveRating');
        Route::get('order_detail/{order_id}/{status}', [\App\Http\Controllers\Front\WishlistProducts::class, 'orderDetail'])->name('order_detail');



        Route::get('order_confirm', [\App\Http\Controllers\Front\CartController::class, 'orderConfirm'])->name('orderConfirm');


    });
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends \Spatie\Permission\Models\Role
{
    use HasFactory;
    protected $with = ["permissions"];
    protected $fillable = ['name','guard'];
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\HelperModule;
use App\Models\Permission;
use App\Models\User;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\Validator;
class RoleController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:role-list');
        $this->middleware('permission:role-create', ['only' => ['create','store']]);
        $this->middleware('permission:role-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:role-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $roles = Role::all();

        if ($request->ajax()) {
            return Datatables::of($roles)
                ->addIndexColumn()
                ->addColumn('action', function($row){
                    $btn = '<a href="'.route('roles.edit',[$row->id]).'" class="edit btn btn-primary btn-sm"><i class="flaticon-edit-1"></i></a>
                            <a href="javascript:void(0)" class="edit btn btn-danger btn-sm" id="'.$row->id.'" onclick="deleteRole(this)"><i class="la la-trash"></i></a>';
                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }

        return view('admin.roles.index',compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::all();
        return view('admin.roles.create',compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $form_data = $request->all();
        $rules = array(
            'name' => "required",
//            'permission' => "required",
        );
        $validator = Validator::make($form_data, $rules);
        if ($validator->fails()) {
            return back()->with('error',$validator->errors()->first());
        }

        $role = Role::create(['name' => $request->input('name')]);
        $role->syncPermissions($request->input('permission_id'));
        return redirect()->route('roles.index')
            ->with('success','Role created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::with('permissions')->find($id);
        $permissions = Permission::all();
        return view('admin.roles.edit',compact('role','permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $form_data = $request->all();
        $rules = array(
            'name' => "required",
//            'permission' => "required",
        );
        $validator = Validator::make($form_data, $rules);
        if ($validator->fails()) {
            return back()->with('error',$validator->errors()->first());
        }

        $role = Role::find($id);
        $role->name = $request->input('name');
        $role->save();
        $role->syncPermissions($request->input('permission_id'));
        return redirect()->route('roles.index')
            ->with('success','Role Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::find($id);
        if($role->delete()){
            return response()->json(['status' =>200,'message' => 'Role Deleted Successfully']);
        }else{
            return response()->json(['status' =>404,'message' => 'Role Not found']);
        }
    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts.master')
@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        Create Roles
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <form method="post" action="{{route('roles.store')}}" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control" required>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Guard</label>
                            <input type="text" name="price_min" class="form-control" value="web" readonly required>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <th><input type="checkbox" name="select_all_permissions" id="checkAll" class="permission_checkbox"></th>
{{--                            <th>Module Name</th>--}}
                            <th>Permission Name</th>
                        </thead>
                        <tbody>
                        @foreach($permissions as $key => $permisson)
                            <tr>
                                <td>
                                    <input type="checkbox" name="permission_id[]" value="{!! $permisson->id !!}"
                                           class="permission_checkbox" id="select_permission-{!! $permisson->id !!}">
                                </td>
{{--                                <td>{!! $permisson->module->name !!}</td>--}}
                                <td>{!! $permisson->name !!}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <button type="submit" class="btn btn-primary">
                    Create User
                </button>
            </form>
        </div>

    </div>

@endsection
@push('javascript_section')
    <script type="text/javascript">
        $("#checkAll").click(function(){
            $('input:checkbox').not(this).prop('checked', this.checked);
        });
    </script>
@endpush

resources/views/admin/roles/edit.blade.php
@extends('layouts.master')
@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        Create Roles
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <form method="post" action="{{route('roles.update',[$role->id])}}" enctype="multipart/form-data">
                @csrf
                @method('PATCH')
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control" value="{!! $role->name !!}" required>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Guard</label>
                            <input type="text" name="price_min" class="form-control" value="web" readonly required>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <table class="table table-striped table-bordered">
                        <thead>
                        <th><input type="checkbox" name="select_all_permissions" id="checkAll" class="permission_checkbox"></th>
                        <th>Module Name</th>
                        <th>Permission Name</th>
                        </thead>
                        <tbody>
                        @foreach($permissions as $key => $permisson)
                            @php
                                $roles_permissions = $role->permissions->pluck('id')->toArray();
                            @endphp
                            <tr>
                                <td>
                                    <input type="checkbox" name="permission_id[]" value="{!! $permisson->id !!}"
                                           class="permission_checkbox" id="select_permission-{!! $permisson->id !!}"
                                    @if(in_array($permisson->id,$roles_permissions)) checked @endif>
                                </td>
                                <td>{{--{!! $permisson->module->name !!}--}}</td>
                                <td>{!! $permisson->name !!}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <button type="submit" class="btn btn-primary">
                   Update
                </button>
            </form>
        </div>

    </div>

@endsection
@push('javascript_section')
    <script type="text/javascript">
        $("#checkAll").click(function(){
            $('input:checkbox').not(this).prop('checked', this.checked);
        });
    </script>
@endpush

resources/views/admin/roles/index.blade.php
@extends('layouts.master')
@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        All Roles
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <!--begin: Datatable -->
            <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                @if ($message = Session::get('success'))
                    <div class="alert alert-success alert-dismissible fade show">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                        <p>{{ $message }}</p>
                    </div>
                @endif
                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong>Something went wrong.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="row align-items-center">
                    <div class="col-xl-4 order-1 order-xl-2 ">
                        <a href="{{route('roles.create')}}" type="button" class="btn btn-primary">
                            <span>
                                <i class="la la-cart-plus"></i>
                                <span>Add New</span>
                            </span>
                        </a>
                        <div class="m-separator m-separator--dashed d-xl-none"></div>
                    </div>
                </div>
            </div>
            <table class="table table-bordered data-table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Guard</th>
                    <th width="100px">Action</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            <!--end: Datatable -->
        </div>
    </div>
    <!--begin::Modal-->
    <div id="myModal" class="modal fade">
        <div class="modal-dialog modal-confirm">
            <div class="modal-content">
                <div class="modal-header flex-column">
                    <div class="icon-box">
                        <i class="material-icons">&#xE5CD;</i>
                    </div>
                    <h4 class="modal-title w-100">Are you sure?</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <p>Do you really want to delete these records? This process cannot be undone.</p>
                </div>
                <div class="modal-footer justify-content-center">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-danger" id="delete_inner_btn">Delete</button>
                </div>
            </div>
        </div>
    </div>
    <!--end::Modal-->
@endsection

@push('javascript_section')
    <script type="text/javascript">
        $(function () {

            var table = $('.data-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('roles.index') }}",
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'name', name: 'name'},
                    {data: 'guard_name', name: 'guard_name'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });
        });

        function deleteRole(e) {
            $('#delete_inner_btn').attr('data-info', e.id);
            $('#myModal').modal('show');
        }
        $('#delete_inner_btn').click(function (e) {
            var id = $(this).data('info');
            $.ajax({
                type: "DELETE",
                url: 'roles/'+id,
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                data: {
                    "id": id,
                    "method": "DELETE",
                },
                success: function (result) {
                   if(result.status == 200){
                       toastr.success(result.message);
                       $('#myModal').modal('hide');
                   }else{
                       toastr.error(result.message);
                       $('#myModal').modal('hide');
                   }
                }
            });
        })
    </script>
@endpush

resources/views/admin/roles/permissions.blade.php
@extends('layouts.master')
@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        All Permissions
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                @if ($message = Session::get('success'))
                    <div class="alert alert-success alert-dismissible fade show">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                        <p>{{ $message }}</p>
                    </div>
                @endif
                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong>Something went wrong.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="row align-items-center">
                    <div class="col-xl-4 order-1 order-xl-2 ">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#m_modal_4" >
                            <span>
                                <i class="la la-cart-plus"></i>
                                <span>Add New</span>
                            </span>
                        </button>
                        <div class="m-separator m-separator--dashed d-xl-none"></div>
                    </div>
                </div>
            </div>
            <!--begin: Datatable -->
            <table class="table table-bordered data-table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
{{--                    <th>Module</th>--}}
{{--                    <th width="100px">Action</th>--}}
                </tr>
                </thead>
                <tbody>
                @if(count($permissions))
                @foreach($permissions as $key => $permission)
                    <tr>
                        <td>{!! ++$key !!}</td>
                        <td>{!! $permission->name !!}</td>
{{--                        <td>{!! $permission->module->name !!}</td>--}}
                    </tr>
                @endforeach
                @else
                    <tr>
                        <td>No record found</td>
                    </tr>
                @endif
                </tbody>
            </table>
            <!--end: Datatable -->
        </div>
    </div>
    <!--begin::Modal-->
    <div class="modal fade" id="m_modal_4" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog " role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">
                        New Permissions
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
											<span aria-hidden="true">
												&times;
											</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" action="{{route('permissions.store')}}" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Name</label>
                                    <input type="text" name="name" class="form-control" required>
                                </div>
                            </div>
{{--                            <div class="col-md-6">--}}
{{--                                <div class="form-group">--}}
{{--                                    <label>Choose Module</label>--}}
{{--                                    <select name="module_id" class="form-control" id="module_id">--}}
{{--                                      @foreach($modules as $key => $module)--}}
{{--                                          <option value="{!! $module->id !!}">{!! $module->name !!}</option>--}}
{{--                                      @endforeach--}}
{{--                                    </select>--}}
{{--                                </div>--}}
{{--                            </div>--}}
                        </div>
                        <button type="submit" class="btn btn-primary">
                            Create
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!--end::Modal-->
@endsection

@push('javascript_section')
@endpush