routes/web.php
<?php

use App\Models\Category;
use App\Models\Color;
use App\Models\Size;
use App\Models\Vendor;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ColorController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\GeneralSettingsController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\Front\CustomerController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->to('home');

});
Route::get('/home', [\App\Http\Controllers\Front\PagesController::class, 'index'])->name('home');

Route::view('/admin/login', 'admin.login');

Route::get('login-popup', function () {
    return view('front.loginPopup');
});

Route::get('add-address', function () {
    return view('front.addAddress');
});
Route::view('contact-us', 'front.contact-us');

// Route::view('/dashboard', 'admin.index')->middleware(['auth'])->name('dashboard');
Route::get('/dashboard', [\App\Http\Controllers\HomeController::class, 'index'])->middleware(['auth'])->name('dashboard');
\Illuminate\Support\Facades\Auth::routes();
//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//---------------------------Routes for guest users of front site--------------------------------------//
Route::group(['namespace' => 'Front'], function () {
    Route::get('product-list/{category_name}', [\App\Http\Controllers\Front\ProductController::class, 'getProducts'])->name('getProducts');
    Route::get('product-detail/{id}', [\App\Http\Controllers\Front\ProductController::class, 'productDetail'])->name('productDetail');
    Route::get('product_category_filter', [\App\Http\Controllers\Front\ProductController::class, 'categoryFilter'])->name('categoryFilter');
    Route::get('product_name_filter', [\App\Http\Controllers\Front\ProductController::class, 'productNameFilter'])->name('productNameFilter');
    Route::get('product_price_filter', [\App\Http\Controllers\Front\ProductController::class, 'priceFilter'])->name('priceFilter');
    Route::get('get-color-sizes/{color_id}/{variant_id}', [\App\Http\Controllers\Front\ProductController::class, 'getColorSizes'])->name('getColorSizes');
    Route::get('product_size-filter/{type}/{min}/{max}/{size}', [\App\Http\Controllers\Front\ProductController::class, 'sizeFilter'])->name('sizeFilter');
    Route::get('product_color-filter/{type}/{min}/{max}/{size}', [\App\Http\Controllers\Front\ProductController::class, 'colorFilter'])->name('colorFilter');
    Route::get('product_size_color-filter/{type}/{min}/{max}/{size}/{color}', [\App\Http\Controllers\Front\ProductController::class, 'sizeColorFilter'])->name('sizeColorFilter');
    Route::get('product_wishlist_update/{product_id}/{variant_id}', [\App\Http\Controllers\Front\ProductController::class, 'productWishlistUpdate'])->name('productWishlistUpdate');
    Route::get('trackOrder', [\App\Http\Controllers\Front\ProductController::class, 'trackOrder'])->name('trackOrder');

   Route::get('product_search_filter/{search}/{color}/{size}/{min_max}/{price_limit}', [\App\Http\Controllers\Front\ProductController::class, 'productSearchFiter'])->name('productSearchFiter');
   Route::get('product_category_filter/{search}/{color}/{size}/{min_max}/{price_limit}', [\App\Http\Controllers\Front\ProductController::class, 'productCategoryFiter'])->name('productCategoryFiter');

     Route::get('clear_cart', [\App\Http\Controllers\Front\CartController::class, 'clearCart'])->name('clearCart');

});

Route::get('cart', [\App\Http\Controllers\Front\WishlistProducts::class, 'cartItems'])->name('cart');
Route::get('product_cart_update/{variant_id}/{qty?}', [\App\Http\Controllers\Front\WishlistProducts::class, 'productCartUpdate'])->name('productCartUpdate');
Route::get('remove-cart-item/{variant_id}', [\App\Http\Controllers\Front\WishlistProducts::class, 'removeCartItem'])->name('removeCartItem');
Route::get('get-cart-item', [\App\Http\Controllers\Front\WishlistProducts::class, 'getCartItems'])->name('getCartItems');


Route::get('check_coupon_validity/{coupon}', [\App\Http\Controllers\Front\CartController::class, 'checkCouponValidity'])->name('checkCouponValidity');


Route::middleware(['auth'])->group(function () {
    Route::resource('roles', RoleController::class);
    Route::get('admin-profile',[UserController::class,'adminProfile'])->name('adminProfile');
    Route::resource('users', UserController::class);
    Route::resource('permissions', PermissionController::class);
    Route::resource('colors', ColorController::class);
    Route::resource('sizes', \App\Http\Controllers\SizeController::class);
    Route::get('category_images', [CategoriesController::class, 'getCategoryImages'])->name('getCategoryImages');
    Route::resource('categories', CategoriesController::class);
    Route::get('get_images', [ProductController::class, 'getImages'])->name('getImages');
    Route::post('storeProduct', [ProductController::class, 'storeProduct'])->name('storeProduct');
//    Route::get('/product', function () {});
    Route::get('products/variants/{id}', [ProductController::class, 'getProdcutVariant'])->name('get_product_variant');
    Route::get('products/edit_variants/{variant_id}', [ProductController::class, 'editVariant'])->name('edit_variant');
    Route::post('products/update_variants/{variant_id}', [ProductController::class, 'updateVariant'])->name('update_variant');
    Route::delete('products_variants_delete/{variant_id}', [ProductController::class, 'deleteVariant'])->name('delete_variant');
    Route::resource('products', ProductController::class);
    Route::resource('general-settings', GeneralSettingsController::class);
    Route::get('assign-coupon-page',[CouponController::class,'assignCouponsList'])->name('assignCouponsList');
    Route::get('get-remaining-coupons',[CouponController::class,'getRemainingCouponsToAssign'])->name('getRemainingCouponsToAssign');
    Route::post('search-customer',[CouponController::class,'searchCustomer'])->name('searchCustomer');
    Route::post('assign-coupons',[CouponController::class,'assignCouponToCustomer'])->name('assignCouponToCustomer');
    Route::resource('coupons', CouponController::class);
    Route::resource('banners', \App\Http\Controllers\BannerController::class);
    Route::get('banner_images', [\App\Http\Controllers\BannerController::class, 'getBannerImages'])->name('getBannerImages');
    Route::post('getFirstcategory', [ProductController::class, 'getFirstcategory'])->name('getFirstcategory');
    Route::post('getSecondChildCategory', [ProductController::class, 'getSecondChildCategory'])->name('getSecondChildCategory');

    Route::get('orders-page', [\App\Http\Controllers\OrderController::class, 'index'])->name('orders');
    Route::get('changeOrderStatus/{id}', [\App\Http\Controllers\OrderController::class, 'changeStatus'])->name('changeStatus');
    Route::get('updateStatus', [\App\Http\Controllers\OrderController::class, 'updateStatus'])->name('updateStatus');


    Route::get('/failed_jobs', [\App\Http\Controllers\JobController::class, 'index'])->name('jobs.index');

   Route::get('/job/retry/{id}', function ($id) {

    Artisan::call('config:cache');
    Artisan::queue('queue:restart');

    sleep(2);
      $exitCode = Artisan::call('queue:retry', [
        'id' => $id
    ]);
   return Redirect::back();
});

    Route::group(['namespace' => 'Front'], function () {
        Route::post('update_profile', [CustomerController::class, 'updateProfile'])->name('update_profile');
        Route::post('save_address', [\App\Http\Controllers\Front\WishlistProducts::class, 'saveAddress'])->name('save_address');
        Route::get('change_address_status/{id}/{status}', [\App\Http\Controllers\Front\WishlistProducts::class, 'changeAddressStatus'])->name('changeAddressStatus');
        Route::get('profile', [\App\Http\Controllers\Front\WishlistProducts::class, 'cartOrders'])->name('cartOrders');
        Route::get('wishlist', [\App\Http\Controllers\Front\WishlistProducts::class, 'index'])->name('wishlist');
        Route::get('remove-wishlist/{id}/{variant_id}', [\App\Http\Controllers\Front\WishlistProducts::class, 'removeWishlistItem'])->name('removeWishlistItem');
        /*
                Route::get('remove-cart-item/{variant_id}', [\App\Http\Controllers\Front\WishlistProducts::class, 'removeCartItem'])->name('removeCartItem');
        */
        //Route::post('order-place', [\App\Http\Controllers\Front\WishlistProducts::class, 'orderPlace'])->name('orderPlace');
        Route::post('orderPlace', [\App\Http\Controllers\Front\WishlistProducts::class, 'orderPlace'])->name('orderPlace');
        Route::post('save-rating/{product_id}/{variant_id}', [\App\Http\Controllers\Front\WishlistProducts::class, 'saveRating'])->name('saveRating');
        Route::get('order_detail/{order_id}/{status}', [\App\Http\Controllers\Front\WishlistProducts::class, 'orderDetail'])->name('order_detail');



        Route::get('order_confirm', [\App\Http\Controllers\Front\CartController::class, 'orderConfirm'])->name('orderConfirm');


    });
});

app/Models/Color.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Color extends Model
{
    use HasFactory;
    protected $fillable = ['name','title','is_active'];
}

app/Http/Controllers/ColorController.php
<?php

namespace App\Http\Controllers;

use App\Models\Color;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Yajra\DataTables\DataTables;

class ColorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $colors = Color::where('is_active',1)->get();
        if ($request->ajax()) {
            return Datatables::of($colors)
                ->addIndexColumn()
                ->addColumn('action', function($row){
                    $btn = '<a href="javascript:void(0)" class="edit btn btn-primary btn-sm edit_button" id="'.$row->id.'" onclick="editColor(this)"><i class="flaticon-edit-1"></i></a>
                            <a href="javascript:void(0)" class="edit btn btn-danger btn-sm" id="'.$row->id.'" onclick="deleteColor(this)"><i class="la la-trash"></i></a>';
                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }

        return view('admin.colors.index',compact('colors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
        ]);

        $input = $request->all();
        $input['type'] = $input['name'];
        $user = Color::create($input);
        return redirect()->route('colors.index')
            ->with('success','Color created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $color = Color::find($id);
            return response()->json(['status' => 200, 'message'=> 'Color details','data'=> $color]);
        }catch (\Exception $exception){
            return response()->json(['status' => 422, 'message'=> $exception->getMessage()]);

        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $this->validate($request, [
                'name' => 'required',
            ]);
            $color = Color::find($id);
            $color->name = $request->get('name');
            $color->save();
            return response()->json(['status' => 200, 'message'=> 'Color Updated','data'=> $color]);
        }catch (\Exception $exception){
            return response()->json(['status' => 422, 'message'=> $exception->getMessage()]);

        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Color::find($id);
        if($role->delete()){
            return response()->json(['status' =>200,'message' => 'Color Deleted Successfully']);
        }else{
            return response()->json(['status' =>404,'message' => 'Color Not found']);
        }
    }
}

resources/views/admin/colors/index.blade.php
@extends('layouts.master')
@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        All Colors
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                @if ($message = Session::get('success'))
                    <div class="alert alert-success alert-dismissible fade show">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                        <p>{{ $message }}</p>
                    </div>
                @endif
                @if (count($errors) > 0)
                    <div class="alert alert-danger alert-dismissible fade show">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                        <strong>Whoops!</strong>Something went wrong.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="row align-items-center">
                    <div class="col-xl-4 order-1 order-xl-2 ">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#m_modal_4">
                            <span>
                                <i class="la la-cart-plus"></i>
                                <span>Add New</span>
                            </span>
                        </button>
                        <div class="m-separator m-separator--dashed d-xl-none"></div>
                    </div>
                </div>
            </div>
            <!--begin: Datatable -->
            <table class="table table-bordered data-table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th width="100px">Action</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            <!--end: Datatable -->
        </div>
    </div>
    <!--begin::Modal-->
    <div class="modal fade" id="m_modal_4" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">
                        New Color
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
											<span aria-hidden="true">
												&times;
											</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" action="{{route('colors.store')}}" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Name</label>
                                    <input type="text" name="name" class="form-control" required>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">
                            Create
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!--end::Modal-->
    <!--begin::Modal-->
    <div class="modal fade" id="edit_color_popup" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">
                        New Color
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
											<span aria-hidden="true">
												&times;
											</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" action="#" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Name</label>
                                    <input type="text" name="name" class="form-control" id="c_name" required>
                                </div>
                            </div>
                        </div>
                        <button type="button" class="btn btn-primary" id="update">
                            Update
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!--end::Modal-->
    <!--begin::Modal-->
    <div id="myModal" class="modal fade">
        <div class="modal-dialog modal-confirm">
            <div class="modal-content">
                <div class="modal-header flex-column">
                    <div class="icon-box">
                        <i class="material-icons">&#xE5CD;</i>
                    </div>
                    <h4 class="modal-title w-100">Are you sure?</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <p>Do you really want to delete these records? This process cannot be undone.</p>
                </div>
                <div class="modal-footer justify-content-center">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-danger" id="delete_inner_btn">Delete</button>
                </div>
            </div>
        </div>
    </div>
    <!--end::Modal-->
@endsection

@push('javascript_section')
    <script type="text/javascript">
        $(function () {

            var table = $('.data-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('colors.index') }}",
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'name', name: 'name'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });
        });

        function editColor(e) {
           var id = e.id;
            url = "colors";
            editUrl = url + '/' + id + '/edit';
            $.ajax({
                type: "GET",
                url: editUrl,
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                success: function (result) {
                    if(result.status == 200){
                        $('#c_name').val(result.data.name)
                        $('#update').attr('data-info', e.id);
                        $('#edit_color_popup').modal('show');
                    }else{
                        toastr.error(result.message);
                        $('#edit_color_popup').modal('hide');
                    }
                }
            });
        }
        $('#update').click(function (e) {
            var id = $(this).data('info');
            var url = 'colors/'+id
            $.ajax({
                type: "post",
                url: url,
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                data: { name:$('#c_name').val(), _method:"PATCH" },
                success: function (result) {
                    if(result.status == 200){
                        toastr.success(result.message);
                        $('#edit_color_popup').modal('hide');
                        $('#'+id).parents('tr').find('td').eq(1).text(result.data.name)
                    }else{
                        toastr.error(result.message);
                        $('#edit_color_popup').modal('hide');
                    }
                }
            });
        });
        function deleteColor(e) {
            $('#delete_inner_btn').attr('data-info', e.id);
            $('#myModal').modal('show');
        }
        $('#delete_inner_btn').click(function (e) {
            var id = $(this).data('info');
            $.ajax({
                type: "DELETE",
                url: 'colors/'+id,
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                data: {
                    "id": id,
                    "method": "DELETE",
                },
                success: function (result) {
                    if(result.status == 200){
                        toastr.success(result.message);
                        $('#myModal').modal('hide');
                        $('#'+id).parents('tr').remove();
                    }else{
                        toastr.error(result.message);
                        $('#myModal').modal('hide');
                    }
                }
            });
        })
    </script>
@endpush