routes/web.php
<?php

use App\Models\Category;
use App\Models\Color;
use App\Models\Size;
use App\Models\Vendor;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ColorController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\GeneralSettingsController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\Front\CustomerController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->to('home');

});
Route::get('/home', [\App\Http\Controllers\Front\PagesController::class, 'index'])->name('home');

Route::view('/admin/login', 'admin.login');

Route::get('login-popup', function () {
    return view('front.loginPopup');
});

Route::get('add-address', function () {
    return view('front.addAddress');
});
Route::view('contact-us', 'front.contact-us');

// Route::view('/dashboard', 'admin.index')->middleware(['auth'])->name('dashboard');
Route::get('/dashboard', [\App\Http\Controllers\HomeController::class, 'index'])->middleware(['auth'])->name('dashboard');
\Illuminate\Support\Facades\Auth::routes();
//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//---------------------------Routes for guest users of front site--------------------------------------//
Route::group(['namespace' => 'Front'], function () {
    Route::get('product-list/{category_name}', [\App\Http\Controllers\Front\ProductController::class, 'getProducts'])->name('getProducts');
    Route::get('product-detail/{id}', [\App\Http\Controllers\Front\ProductController::class, 'productDetail'])->name('productDetail');
    Route::get('product_category_filter', [\App\Http\Controllers\Front\ProductController::class, 'categoryFilter'])->name('categoryFilter');
    Route::get('product_name_filter', [\App\Http\Controllers\Front\ProductController::class, 'productNameFilter'])->name('productNameFilter');
    Route::get('product_price_filter', [\App\Http\Controllers\Front\ProductController::class, 'priceFilter'])->name('priceFilter');
    Route::get('get-color-sizes/{color_id}/{variant_id}', [\App\Http\Controllers\Front\ProductController::class, 'getColorSizes'])->name('getColorSizes');
    Route::get('product_size-filter/{type}/{min}/{max}/{size}', [\App\Http\Controllers\Front\ProductController::class, 'sizeFilter'])->name('sizeFilter');
    Route::get('product_color-filter/{type}/{min}/{max}/{size}', [\App\Http\Controllers\Front\ProductController::class, 'colorFilter'])->name('colorFilter');
    Route::get('product_size_color-filter/{type}/{min}/{max}/{size}/{color}', [\App\Http\Controllers\Front\ProductController::class, 'sizeColorFilter'])->name('sizeColorFilter');
    Route::get('product_wishlist_update/{product_id}/{variant_id}', [\App\Http\Controllers\Front\ProductController::class, 'productWishlistUpdate'])->name('productWishlistUpdate');
    Route::get('trackOrder', [\App\Http\Controllers\Front\ProductController::class, 'trackOrder'])->name('trackOrder');

   Route::get('product_search_filter/{search}/{color}/{size}/{min_max}/{price_limit}', [\App\Http\Controllers\Front\ProductController::class, 'productSearchFiter'])->name('productSearchFiter');
   Route::get('product_category_filter/{search}/{color}/{size}/{min_max}/{price_limit}', [\App\Http\Controllers\Front\ProductController::class, 'productCategoryFiter'])->name('productCategoryFiter');

     Route::get('clear_cart', [\App\Http\Controllers\Front\CartController::class, 'clearCart'])->name('clearCart');

});

Route::get('cart', [\App\Http\Controllers\Front\WishlistProducts::class, 'cartItems'])->name('cart');
Route::get('product_cart_update/{variant_id}/{qty?}', [\App\Http\Controllers\Front\WishlistProducts::class, 'productCartUpdate'])->name('productCartUpdate');
Route::get('remove-cart-item/{variant_id}', [\App\Http\Controllers\Front\WishlistProducts::class, 'removeCartItem'])->name('removeCartItem');
Route::get('get-cart-item', [\App\Http\Controllers\Front\WishlistProducts::class, 'getCartItems'])->name('getCartItems');


Route::get('check_coupon_validity/{coupon}', [\App\Http\Controllers\Front\CartController::class, 'checkCouponValidity'])->name('checkCouponValidity');


Route::middleware(['auth'])->group(function () {
    Route::resource('roles', RoleController::class);
    Route::get('admin-profile',[UserController::class,'adminProfile'])->name('adminProfile');
    Route::resource('users', UserController::class);
    Route::resource('permissions', PermissionController::class);
    Route::resource('colors', ColorController::class);
    Route::resource('sizes', \App\Http\Controllers\SizeController::class);
    Route::get('category_images', [CategoriesController::class, 'getCategoryImages'])->name('getCategoryImages');
    Route::resource('categories', CategoriesController::class);
    Route::get('get_images', [ProductController::class, 'getImages'])->name('getImages');
    Route::post('storeProduct', [ProductController::class, 'storeProduct'])->name('storeProduct');
//    Route::get('/product', function () {});
    Route::get('products/variants/{id}', [ProductController::class, 'getProdcutVariant'])->name('get_product_variant');
    Route::get('products/edit_variants/{variant_id}', [ProductController::class, 'editVariant'])->name('edit_variant');
    Route::post('products/update_variants/{variant_id}', [ProductController::class, 'updateVariant'])->name('update_variant');
    Route::delete('products_variants_delete/{variant_id}', [ProductController::class, 'deleteVariant'])->name('delete_variant');
    Route::resource('products', ProductController::class);
    Route::resource('general-settings', GeneralSettingsController::class);
    Route::get('assign-coupon-page',[CouponController::class,'assignCouponsList'])->name('assignCouponsList');
    Route::get('get-remaining-coupons',[CouponController::class,'getRemainingCouponsToAssign'])->name('getRemainingCouponsToAssign');
    Route::post('search-customer',[CouponController::class,'searchCustomer'])->name('searchCustomer');
    Route::post('assign-coupons',[CouponController::class,'assignCouponToCustomer'])->name('assignCouponToCustomer');
    Route::resource('coupons', CouponController::class);
    Route::resource('banners', \App\Http\Controllers\BannerController::class);
    Route::get('banner_images', [\App\Http\Controllers\BannerController::class, 'getBannerImages'])->name('getBannerImages');
    Route::post('getFirstcategory', [ProductController::class, 'getFirstcategory'])->name('getFirstcategory');
    Route::post('getSecondChildCategory', [ProductController::class, 'getSecondChildCategory'])->name('getSecondChildCategory');

    Route::get('orders-page', [\App\Http\Controllers\OrderController::class, 'index'])->name('orders');
    Route::get('changeOrderStatus/{id}', [\App\Http\Controllers\OrderController::class, 'changeStatus'])->name('changeStatus');
    Route::get('updateStatus', [\App\Http\Controllers\OrderController::class, 'updateStatus'])->name('updateStatus');


    Route::get('/failed_jobs', [\App\Http\Controllers\JobController::class, 'index'])->name('jobs.index');

   Route::get('/job/retry/{id}', function ($id) {

    Artisan::call('config:cache');
    Artisan::queue('queue:restart');

    sleep(2);
      $exitCode = Artisan::call('queue:retry', [
        'id' => $id
    ]);
   return Redirect::back();
});

    Route::group(['namespace' => 'Front'], function () {
        Route::post('update_profile', [CustomerController::class, 'updateProfile'])->name('update_profile');
        Route::post('save_address', [\App\Http\Controllers\Front\WishlistProducts::class, 'saveAddress'])->name('save_address');
        Route::get('change_address_status/{id}/{status}', [\App\Http\Controllers\Front\WishlistProducts::class, 'changeAddressStatus'])->name('changeAddressStatus');
        Route::get('profile', [\App\Http\Controllers\Front\WishlistProducts::class, 'cartOrders'])->name('cartOrders');
        Route::get('wishlist', [\App\Http\Controllers\Front\WishlistProducts::class, 'index'])->name('wishlist');
        Route::get('remove-wishlist/{id}/{variant_id}', [\App\Http\Controllers\Front\WishlistProducts::class, 'removeWishlistItem'])->name('removeWishlistItem');
        /*
                Route::get('remove-cart-item/{variant_id}', [\App\Http\Controllers\Front\WishlistProducts::class, 'removeCartItem'])->name('removeCartItem');
        */
        //Route::post('order-place', [\App\Http\Controllers\Front\WishlistProducts::class, 'orderPlace'])->name('orderPlace');
        Route::post('orderPlace', [\App\Http\Controllers\Front\WishlistProducts::class, 'orderPlace'])->name('orderPlace');
        Route::post('save-rating/{product_id}/{variant_id}', [\App\Http\Controllers\Front\WishlistProducts::class, 'saveRating'])->name('saveRating');
        Route::get('order_detail/{order_id}/{status}', [\App\Http\Controllers\Front\WishlistProducts::class, 'orderDetail'])->name('order_detail');



        Route::get('order_confirm', [\App\Http\Controllers\Front\CartController::class, 'orderConfirm'])->name('orderConfirm');


    });
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $fillable = ['parent_id','level','category_order','name','slug',
        'short_description','created_by','update_by','is_active'];

//    protected $with = ["childCategory"];

    public function parentCategory(){
        return $this->belongsTo(Category::class,'parent_id');
    }

    public function childCategory(){
        return $this->hasMany(Category::class,'parent_id');
    }

    public function getCreatedByAttribute($value){
        return User::find($value)->f_name;
    }

    public function user(){
        return $this->belongsTo(User::class,'created_by');
    }

    public function image(){
        return $this->morphMany( Image::class,'model');
    }

    public function products(){
        return $this->hasMany(Product::class,'category_id');
    }
    public function childCatProducts(){
        return $this->hasMany(Product::class,'first_child_category');
    }
}

resources/views/admin/categories/edit.blade.php
@extends('layouts.master')
@section('content')
    <style>
    </style>
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">Edit Category</h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <form method="post" enctype="multipart/form-data" action="{{route('categories.update',[$category->id])}}" id="category_edit_form">
                @csrf
                @method('PATCH')
                <input type="hidden" value="{!! $category->id !!}" id="category_id">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control" id="name" value="{!! $category->name !!}" required>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Parent Category</label>
                            <select name="parent_id" class="form-control" id="parent_id_edit">
                                <option value="">Choose Parent Category</option>
                                @foreach($categories as $key => $cat)
                                    <option value="{!! $cat->id !!}" @if($cat->id == $category->parent_id) selected @endif>{!! $cat->name !!}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Description</label>
                            <textarea name="short_description" class="form-control" required id="short_description">
                                {!! trim($category->short_description) !!}
                            </textarea>
                        </div>
                    </div>

                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="input-images-edit"></div>
                    </div>

                </div>
                <button type="submit" class="btn btn-primary" id="update">
                    Update
                </button>
            </form>
        </div>

    </div>

@endsection
@push('javascript_section')
    <!--begin::Page Resources -->
    <script type="text/javascript">

        $(function () {
            $('.input-images-edit').empty();
            var category_id = $('#category_id').val();
            $.ajax({
                type: "GET",
                url: '{{url('category_images')}}',
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                data:{id:category_id},
                success: function (result) {
                    $('.input-images-edit').imageUploader({
                        preloaded: result.data,
                        imagesInputName: 'images',
                        preloadedInputName: 'old'
                    });
                    $('#edit_category_popup').modal('show');
                }
            });
        });
    </script>
@endpush

resources/views/admin/categories/index.blade.php
@extends('layouts.master')
@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        All Categories
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                @if ($message = Session::get('success'))
                    <div class="alert alert-success alert-dismissible fade show">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                        <p>{{ $message }}</p>
                    </div>
                @endif
                @if ($message = Session::get('error'))
                    <div class="alert alert-danger alert-dismissible fade show">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                        <p>{{ $message }}</p>
                    </div>
                @endif
                @if (count($errors) > 0)
                    <div class="alert alert-danger alert-dismissible fade show">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                        <strong>Whoops!</strong>Something went wrong.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                @can('category-create')
                    <div class="row align-items-center">
                        <div class="col-xl-4 order-1 order-xl-2 ">
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#m_modal_4">
                                <span>
                                    <i class="la la-cart-plus"></i>
                                    <span>Add New</span>
                                </span>
                            </button>
                            <div class="m-separator m-separator--dashed d-xl-none"></div>
                        </div>
                    </div>
                @endcan
            </div>
            <!--begin: Datatable -->
            <table class="table table-bordered data-table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Parent Category</th>
{{--                    <th>Level</th>--}}
{{--                    <th>Order</th>--}}
                    <th>Description</th>
                    <th>Created By</th>
                    <th width="100px">Action</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            <!--end: Datatable -->
        </div>
    </div>
    <!--begin::Modal create -->
    <div class="modal fade" id="m_modal_4" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">
                        New Category
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
											<span aria-hidden="true">
												&times;
											</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" action="{{route('categories.store')}}" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Name</label>
                                    <input type="text" name="name" class="form-control" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Choose Category</label>
                                    <select name="parent_id" class="form-control" id="parent_id">
                                        <option value="">Choose Category</option>
                                        @foreach($categories as $key => $category)
                                            <option value="{!! $category->id !!}">{!! $category->name !!}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Description</label>
                                    <textarea name="short_description" class="form-control" required></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <div class="input-images"></div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">
                            Create
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!--end::Modal-->
    <!--begin::Modal delete-->
    <div id="myModal" class="modal fade">
        <div class="modal-dialog modal-confirm">
            <div class="modal-content">
                <div class="modal-header flex-column">
                    <div class="icon-box">
                        <i class="material-icons">&#xE5CD;</i>
                    </div>
                    <h4 class="modal-title w-100">Are you sure?</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <p>Do you really want to delete these records? This process cannot be undone.</p>
                </div>
                <div class="modal-footer justify-content-center">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-danger" id="delete_inner_btn">Delete</button>
                </div>
            </div>
        </div>
    </div>
    <!--end::Modal-->
@endsection

@push('javascript_section')
    <script type="text/javascript">
        let preloaded;

        $(function () {
                $('.input-images').imageUploader();
            var table = $('.data-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('categories.index') }}",
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'name', name: 'name'},
                    {data: 'parent_cat', name: 'name'},
                    // {data: 'level', name: 'level'},
                    // {data: 'order', name: 'order'},
                    {data: 'short_description', name: 'short_description'},
                    {data: 'created_by', name: 'created_by'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });

        });

        $('#update').click(function (e) {
            var id = $(this).data('info');
            var url = 'categories/'+id
            $('#c_name').val()
            var parent_id = $('#parent_id_edit').val();
            var desc = $('#short_description').text();
            var form_data = new FormData($(this).parent('form')[0]);
            console.log(form_data);
            $.ajax({
                type: "put",
                url: url,
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                data: form_data,
                processData: false,
                contentType: false,
                dataType: 'formData',
                success: function (result) {
                    console.log(result);
                    if(result.status == 200){
                        toastr.success(result.message);
                        $('#edit_category_popup').modal('hide');
                        $('#'+id).parents('tr').find('td').eq(1).text(result.data.name)
                    }else{
                        toastr.error(result.message);
                        $('#edit_category_popup').modal('hide');
                    }
                }
            });
        });
        function deleteColor(e) {
            $('#delete_inner_btn').attr('data-info', e.id);
            $('#myModal').modal('show');
        }
        $('#delete_inner_btn').click(function (e) {
            var id = $(this).data('info');
            $.ajax({
                type: "DELETE",
                url: 'categories/'+id,
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                data: {
                    "id": id,
                    "method": "DELETE",
                },
                success: function (result) {
                    if(result.status == 200){
                        toastr.success(result.message);
                        $('#myModal').modal('hide');
                        $('#'+id).parents('tr').remove();
                    }else{
                        toastr.error(result.message);
                        $('#myModal').modal('hide');
                    }
                }
            });
        })


    </script>
@endpush